Hey you should probably update your library
lovell/detect-libc pull request #24
Opened 2024-08-23 02:01 UTC by AmeerArsala

`node:` is now the standard and cloudflare test deployments on linux dont work without this

2024-08-23 07:38 UTC, lovell commented
Support for the optional `node:` prefix was [added in Node.js 14.18.0](https://nodejs.org/en/blog/release/v14.18.0).

This package is widely depended-upon and currently supports Node.js 8 onwards.

https://github.com/lovell/detect-libc/blob/db8ea62694a6bd274366c2b4d982b13c074537a3/package.json#L38

There is no mention of `child_process` or `fs` at https://developers.cloudflare.com/workers/runtime-apis/nodejs so I can't quite understand how the proposed change will help with deployment to Cloudflare Workers. Are you able to explain this a bit more?

If this is something that is genuinely required then perhaps we could support a fallback, where the `node:` prefixed version of a module is required and on failure the unprefixed version is required instead?

2024-08-23 07:39 UTC, lovell requested changes

2024-08-23 07:39 UTC, lovell commented on README.md
> +**IF YOU ARE READING THIS, YES. THIS ONE IS THE ONE THAT FIXES THE CLOUDFLARE ISSUE. HAVE FUN TESTING IN DEV!**
?

2024-08-23 07:39 UTC, lovell commented on package.json
> +  "name": "@ameerarsala/detect-libc",
?

2024-08-23 07:39 UTC, lovell commented on package.json
> +    "url": "git://github.com/AmeerArsala/detect-libc"
?

2024-08-23 07:39 UTC, lovell commented on package.json
> +  "version": "2.0.4-0",
?

2024-08-23 07:39 UTC, lovell commented on package.json
> +  "author": "Ameer Arsala <ameer.arsala03@gmail.com>",
?

2024-08-24 00:35 UTC, AmeerArsala commented
Yes I'll make those changes! My bad I just needed to get an app working as quickly as possible so i had to publish a fork on npm. Basically, if you want to use certain Node libraries with Cloudflare workers that depend on this package, it won't work. The reason is that Cloudflare workers and all products based off of that (including pages) do not run Node and instead run a stripped-down version of Node called `workerd` as to avoid cold starts. As a result, some of these features require external Node compatibility and you must prefix with `node:`

2024-08-24 07:36 UTC, lovell commented
> if you want to use certain Node libraries with Cloudflare workers that depend on this package

Are you able to share more details about which library/ies you are attempting to use? I ask as many native modules use this package and, even with the proposed changes, may still be unsupported by Cloudflare Workers.

2024-08-24 08:00 UTC, AmeerArsala commented
Oh I already tried it and it worked. Libraries like LibSQL and Sharp depend on it

2024-08-24 09:18 UTC, lovell commented
In terms of Sharp and "it worked", are you talking about Cloudflare Pages or Workers? I ask as the former provides a complete Node.js environment and is known to work already (without the proposed change), the latter uses V8 isolates and is known to not work due to a lack of Web Worker support.

2024-08-24 11:07 UTC, AmeerArsala commented
I'm talking about both, though this may not apply to Pages in prod/staging (it DOES apply in dev when running with the cloudflare runtime locally). It is for sure a thing with workers though.

2024-08-24 13:23 UTC, lovell commented
I've created https://github.com/lovell/detect-libc/issues/25 to track future possible improvements. 

Thanks for taking the time to open this PR and start the discussion. I'll close this PR for now but would be very happy to accept an updated PR that more closely matches what it proposes, if you're able.

2024-08-24 13:23 UTC, closed without merging